permalink: pretty

theme: minima

collections:
  fiches:
    output: true

defaults:
  - scope:
      path: ""
      type: "fiches"
    values:
      layout: "fiche"
  - scope:
      path: ""
    values:
      layout: "default"
      
